    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: Run Ansible playbook
      run: |
        ansible-playbook -i ansible/inventory ansible/playbook.yml

